---
layout: cv
title: Joshua Fuller CV
---


# JOSHUA FULLER
## joshuafulld@gmail.com | (208)-403-4835


### SUMMARY
***

Versatile accountant and data analyst focusing on driving workplace efficiency and delivering meaningful insights. I combine detail-oriented accounting knowledge with technical proficiency in tools like Excel, SQL, and Python to generate actionable results and support informed decision-making.


### EDUCATION
***

**Bachelor of Science: Accounting**  
*September 2022 – April 2026*  
*Brigham Young University – Idaho, Rexburg, ID*

- Senior-year student with completed Auditing and Intermediate Accounting I and II coursework
- Practice preparing balance sheets, income statements, and general ledgers
- Study Generally Accepted Accounting Principles (GAAP) and Generally Accepted Auditing Standards (GAAS)


### SKILLS
***

- Data Analytics: Advanced Excel, VBA, Power BI, ChatGPT-4
- Programming Languages: Python, Pandas, SQL
- Software Proficiencies: Microsoft Office (Word, PowerPoint, Outlook), and Microsoft Teams


### EXPERIENCE
***

**Accessibility Specialist**  
*September 2023 - Present*  
*Brigham Young University-Idaho, Rexburg, ID*

- Maintain detailed spreadsheets for over 100 courses, tracking accessibility issues
- Conduct one-on-one training sessions with 15–30 students per month to analyze and fulfill student needs
- Worked independently to leverage AI tools to automate tasks, increasing audit efficiency by 20%
- Follow through with students and team members to cultivate effective relationships and enhance student experience


### VOLUNTEER EXPERIENCE
***

**Member, Data Science Society**  
*September 2024 - Present*  
*Brigham Young University-Idaho, Rexburg, ID*

- Collaborate with a team to migrate an unstructured 40-sheet Excel database to a streamlined, SQL-based model
- Utilize web scraping techniques to help collect weather data for a separate organization

**Leadership Member, Accounting Society**  
*January 2024 – April 2024*  
*Brigham Young University-Idaho, Rexburg, ID*

- Strengthened the society’s national presence by executing targeted LinkedIn outreach to alumni and professionals
- Managed the official LinkedIn page, promoting events and connecting with industry experts

**Volunteer Missionary**  
*June 2017 – June 2019*  
*Church of Jesus Christ of Latter-day Saints, Indianapolis, Indiana*

- Helped lead technology adoption initiatives to volunteers and train interested parties
- Guided group of 7-9 other missionaries, enhancing their skills through goal setting and coaching


### INTERESTS
***

- Learning Spanish via a language app


<!-- ### Footer

Last updated: May 2013 -->